import { calculateEstimateTotals, getJobCode } from "./domain";
import type {
  AppData,
  Asset,
  Client,
  CreditNote,
  Estimate,
  Expense,
  Invoice,
  Job,
  JobEvent,
  KnowledgeEntry,
  Material,
  PurchaseDocument,
  Supplier,
} from "./types";

function nowIso() {
  return new Date().toISOString();
}

const clients: Client[] = [
  {
    id: "cl-1",
    name: "Bar Piloto",
    type: "bar_negocio",
    phone: "+34 600 111 111",
    email: "barpiloto@example.com",
    address: "Calle Artekale 11, Gernika",
    zone: "Gernika / Busturialdea",
    notes: "Horario fuerte de tarde.",
    tags: ["hostelería"],
    pendingBalance: 186,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    id: "cl-2",
    name: "Maria Etxebarria",
    type: "particular",
    phone: "+34 600 222 222",
    email: "maria.etxebarria@example.com",
    address: "Barrio San Kristobal 4, Muxika",
    zone: "Busturialdea",
    notes: "Prefiere contacto por WhatsApp.",
    tags: ["lavadora"],
    pendingBalance: 0,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    id: "cl-3",
    name: "Comunidad San Juan",
    type: "comunidad",
    phone: "+34 600 333 333",
    email: "administracion@sanjuan.eus",
    address: "Portal San Juan 2, Gernika",
    zone: "Gernika",
    notes: "Necesita parte firmado por portería.",
    tags: ["comunidad"],
    pendingBalance: 0,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    id: "cl-4",
    name: "Caserío Agirre",
    type: "caserio",
    phone: "+34 600 444 444",
    email: "agirre@example.com",
    address: "Caserío Agirre s/n, Ajangiz",
    zone: "Busturialdea",
    notes: "Acceso por pista lateral.",
    tags: ["electrico"],
    pendingBalance: 0,
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
];

const assets: Asset[] = [
  {
    id: "as-1",
    clientId: "cl-2",
    address: "Barrio San Kristobal 4, Muxika",
    category: "lavadora",
    name: "Lavadora principal",
    brand: "Balay",
    model: "3TS986X",
    serial: "BAL-88321",
    location: "Cocina",
    photo: "",
    installationDate: "2020-06-12",
    warrantyUntil: "2026-12-30",
    status: "activo",
    notes: "Bomba ya sustituida en 2024.",
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
  {
    id: "as-2",
    clientId: "cl-3",
    address: "Portal San Juan 2, Gernika",
    category: "alumbrado",
    name: "Alumbrado portal",
    brand: "Philips",
    model: "Coreline LED",
    serial: "LED-3321",
    location: "Portal",
    photo: "",
    installationDate: "2022-03-01",
    warrantyUntil: "2027-03-01",
    status: "activo",
    notes: "Dos averías repetidas por driver.",
    createdAt: nowIso(),
    updatedAt: nowIso(),
  },
];

const materials: Material[] = [
  {
    id: "m-1",
    name: "Enchufe schuko",
    sku: "SCH-01",
    provider: "ElectroNorte",
    category: "mecanismo",
    quantity: 14,
    minimum: 6,
    cost: 4.5,
    salePrice: 8.5,
    location: "Furgón",
    warranty: "2 años",
    compatibility: "mecanismo",
  },
  {
    id: "m-2",
    name: "Interruptor sencillo",
    sku: "INT-02",
    provider: "ElectroNorte",
    category: "mecanismo",
    quantity: 10,
    minimum: 5,
    cost: 5,
    salePrice: 9.5,
    location: "Furgón",
    warranty: "2 años",
    compatibility: "mecanismo",
  },
  {
    id: "m-3",
    name: "Driver LED 24W",
    sku: "DRV-24",
    provider: "LuzPro",
    category: "alumbrado",
    quantity: 4,
    minimum: 4,
    cost: 12,
    salePrice: 22,
    location: "Almacén",
    warranty: "2 años",
    compatibility: "alumbrado",
  },
  {
    id: "m-4",
    name: "Tubo LED",
    sku: "TLED-18",
    provider: "LuzPro",
    category: "alumbrado",
    quantity: 20,
    minimum: 8,
    cost: 7,
    salePrice: 14,
    location: "Almacén",
    warranty: "2 años",
    compatibility: "alumbrado",
  },
  {
    id: "m-5",
    name: "Regleta / clema",
    sku: "RGL-01",
    provider: "ElectroNorte",
    category: "consumible",
    quantity: 36,
    minimum: 10,
    cost: 0.8,
    salePrice: 2,
    location: "Furgón",
    warranty: "1 año",
    compatibility: "otro",
  },
  {
    id: "m-6",
    name: "Bomba desagüe lavadora",
    sku: "BOM-22",
    provider: "Recambios Norte",
    category: "electrodomestico",
    quantity: 2,
    minimum: 2,
    cost: 22,
    salePrice: 42,
    location: "Almacén",
    warranty: "2 años",
    compatibility: "lavadora",
  },
  {
    id: "m-7",
    name: "Latiguillo / tubo flexible",
    sku: "LAT-06",
    provider: "FontaExpress",
    category: "fontaneria",
    quantity: 8,
    minimum: 3,
    cost: 6,
    salePrice: 12,
    location: "Furgón",
    warranty: "2 años",
    compatibility: "lavavajillas",
  },
  {
    id: "m-8",
    name: "Consumibles pequeños",
    sku: "CNS-00",
    provider: "Varios",
    category: "consumible",
    quantity: 50,
    minimum: 15,
    cost: 2,
    salePrice: 5,
    location: "Furgón",
    warranty: "",
    compatibility: "otro",
  },
];

function buildJob(
  input: Partial<Job> & Pick<Job, "id" | "status" | "symptoms" | "priority">,
  sequence: number,
): Job {
  const plannedMaterials = input.plannedMaterials ?? [];
  const totals = calculateEstimateTotals({
    estimatedHours: input.estimatedHours ?? 1,
    distanceKm: input.distanceKm ?? 8,
    urgent: Boolean(input.urgent),
    plannedMaterials,
  });

  return {
    id: input.id,
    code: getJobCode(sequence),
    clientId: input.clientId,
    assetId: input.assetId,
    status: input.status,
    priority: input.priority,
    technician: input.technician ?? "Iker",
    serviceType: input.serviceType ?? "Mantenimiento doméstico",
    requestedAt: input.requestedAt ?? new Date().toISOString().slice(0, 10),
    scheduledAt: input.scheduledAt ?? new Date().toISOString().slice(0, 10),
    completedAt: input.completedAt ?? "",
    origin: input.origin ?? "app",
    symptoms: input.symptoms,
    description: input.description ?? "",
    diagnosis: input.diagnosis ?? "",
    solution: input.solution ?? "",
    address: input.address ?? "",
    zone: input.zone ?? "",
    distanceKm: input.distanceKm ?? 8,
    urgent: Boolean(input.urgent),
    estimatedHours: input.estimatedHours ?? 1,
    realHours: input.realHours ?? 0,
    notesInternal: input.notesInternal ?? "",
    notesClient: input.notesClient ?? "",
    lessons: input.lessons ?? "",
    requiresApproval: Boolean(input.requiresApproval),
    waitingPart: Boolean(input.waitingPart),
    photos: input.photos ?? [],
    plannedMaterials,
    actualMaterials: input.actualMaterials ?? [],
    totals,
  };
}

const jobs: Job[] = [
  buildJob(
    {
      id: "jb-1",
      clientId: "cl-1",
      status: "programado",
      priority: "alta",
      serviceType: "Revisión de alumbrado LED",
      symptoms: "Luces LED del bar no encienden",
      address: "Calle Artekale 11, Gernika",
      zone: "Gernika",
      plannedMaterials: [
        {
          id: "jl-1",
          materialId: "m-3",
          name: "Driver LED 24W",
          qty: 2,
          unitCost: 12,
          salePrice: 22,
          kind: "planned",
        },
      ],
      estimatedHours: 1.5,
      distanceKm: 7,
      requiresApproval: false,
      technician: "Asier",
      origin: "whatsapp",
    },
    1,
  ),
  buildJob(
    {
      id: "jb-2",
      clientId: "cl-2",
      assetId: "as-1",
      status: "pendiente_pieza",
      priority: "media",
      serviceType: "Lavadora no desagua",
      symptoms: "Lavadora Balay no desagua",
      address: "Barrio San Kristobal 4, Muxika",
      zone: "Busturialdea",
      plannedMaterials: [
        {
          id: "jl-2",
          materialId: "m-6",
          name: "Bomba desagüe lavadora",
          qty: 1,
          unitCost: 22,
          salePrice: 42,
          kind: "planned",
        },
      ],
      estimatedHours: 1.5,
      distanceKm: 14,
      requiresApproval: true,
      waitingPart: true,
      technician: "Iker",
      diagnosis: "Bomba dañada por atasco",
      origin: "llamada",
    },
    2,
  ),
  buildJob(
    {
      id: "jb-3",
      clientId: "cl-4",
      status: "facturado",
      priority: "alta",
      serviceType: "Sustitución enchufes",
      symptoms: "Enchufes de cocina con mal contacto",
      address: "Caserío Agirre s/n, Ajangiz",
      zone: "Busturialdea",
      plannedMaterials: [
        {
          id: "jl-3",
          materialId: "m-1",
          name: "Enchufe schuko",
          qty: 2,
          unitCost: 4.5,
          salePrice: 8.5,
          kind: "planned",
        },
        {
          id: "jl-4",
          materialId: "m-8",
          name: "Consumibles pequeños",
          qty: 1,
          unitCost: 2,
          salePrice: 5,
          kind: "planned",
        },
      ],
      estimatedHours: 1,
      realHours: 0.8,
      distanceKm: 19,
      requiresApproval: false,
      technician: "Ane",
      completedAt: new Date().toISOString().slice(0, 10),
      origin: "app",
    },
    3,
  ),
  buildJob(
    {
      id: "jb-4",
      clientId: "cl-1",
      status: "diagnosticado",
      priority: "urgente",
      serviceType: "Lavavajillas pierde agua",
      symptoms: "Pérdida de agua por base inferior",
      address: "Calle Artekale 11, Gernika",
      zone: "Gernika",
      plannedMaterials: [
        {
          id: "jl-5",
          materialId: "m-7",
          name: "Latiguillo / tubo flexible",
          qty: 1,
          unitCost: 6,
          salePrice: 12,
          kind: "planned",
        },
      ],
      estimatedHours: 1.75,
      distanceKm: 6,
      urgent: true,
      requiresApproval: true,
      technician: "Asier",
      diagnosis: "Tubo flexible agrietado",
      origin: "telegram",
    },
    4,
  ),
  buildJob(
    {
      id: "jb-5",
      clientId: "cl-3",
      assetId: "as-2",
      status: "cobrado",
      priority: "media",
      serviceType: "Revisión alumbrado portal",
      symptoms: "Mantenimiento de luminarias y drivers",
      address: "Portal San Juan 2, Gernika",
      zone: "Gernika",
      plannedMaterials: [
        {
          id: "jl-6",
          materialId: "m-4",
          name: "Tubo LED",
          qty: 2,
          unitCost: 7,
          salePrice: 14,
          kind: "planned",
        },
      ],
      estimatedHours: 1.5,
      realHours: 1.5,
      distanceKm: 5,
      technician: "Ane",
      completedAt: new Date().toISOString().slice(0, 10),
      solution: "Sustitución preventiva de tubos LED",
      origin: "formulario",
    },
    5,
  ),
];

const invoices: Invoice[] = [
  {
    id: "inv-1",
    jobId: "jb-3",
    invoiceNumber: "FAC-2026-031",
    subtotal: jobs[2]?.totals.subtotal ?? 0,
    vat: jobs[2]?.totals.vat ?? 0,
    total: jobs[2]?.totals.total ?? 0,
    status: "emitida",
    method: "transferencia",
    issuedAt: new Date().toISOString().slice(0, 10),
    paidAt: "",
    notes: "Pendiente de cobro.",
  },
  {
    id: "inv-2",
    jobId: "jb-5",
    invoiceNumber: "FAC-2026-032",
    subtotal: jobs[4]?.totals.subtotal ?? 0,
    vat: jobs[4]?.totals.vat ?? 0,
    total: jobs[4]?.totals.total ?? 0,
    status: "cobrada",
    method: "bizum",
    issuedAt: new Date().toISOString().slice(0, 10),
    paidAt: new Date().toISOString().slice(0, 10),
    notes: "Cobro confirmado.",
  },
];

const estimates: Estimate[] = [
  {
    id: "est-1",
    jobId: "jb-2",
    clientId: "cl-2",
    status: "enviado",
    sentAt: new Date().toISOString().slice(0, 10),
    approvedAt: "",
    lines: [
      { description: "Diagnóstico", qty: 1, unitPrice: 35 },
      { description: "Bomba desagüe lavadora", qty: 1, unitPrice: 42 },
      { description: "Mano de obra", qty: 1.5, unitPrice: 30 },
    ],
    subtotal: 122,
    vat: 25.62,
    total: 147.62,
  },
];

const expenses: Expense[] = [
  {
    id: "ex-1",
    date: new Date().toISOString().slice(0, 10),
    provider: "Recambios Norte",
    concept: "Compra bombas y consumibles para reparaciones",
    category: "materiales",
    subtotal: 96,
    vat: 20.16,
    total: 116.16,
    paid: true,
    receiptAttached: true,
    notes: "Factura de proveedor lista para gestoría.",
  },
  {
    id: "ex-2",
    date: new Date().toISOString().slice(0, 10),
    provider: "Gasolinera Busturia",
    concept: "Combustible furgoneta técnica",
    category: "vehiculo",
    subtotal: 58.2,
    vat: 12.22,
    total: 70.42,
    paid: true,
    receiptAttached: false,
    notes: "Falta adjuntar ticket.",
  },
  {
    id: "ex-3",
    date: new Date().toISOString().slice(0, 10),
    provider: "Gestoría",
    concept: "Cuota mensual gestión fiscal",
    category: "gestoria",
    subtotal: 75,
    vat: 15.75,
    total: 90.75,
    paid: true,
    receiptAttached: true,
    notes: "",
  },
];

const suppliers: Supplier[] = [
  {
    id: "sp-1",
    name: "Recambios Norte",
    nif: "B48911223",
    phone: "+34 944 111 222",
    email: "pedidos@recambiosnorte.example",
    address: "Polígono Ugaldeguren 8, Zamudio",
    category: "materiales",
    paymentTerms: "Transferencia 30 días",
    notes: "Proveedor principal para lavadoras y pequeños electrodomésticos.",
  },
  {
    id: "sp-2",
    name: "LuzPro",
    nif: "B95770110",
    phone: "+34 944 333 444",
    email: "ventas@luzpro.example",
    address: "Calle Industria 4, Gernika",
    category: "materiales",
    paymentTerms: "Contado",
    notes: "Stock de drivers y tubos LED.",
  },
  {
    id: "sp-3",
    name: "Gasolinera Busturia",
    nif: "B48111999",
    phone: "+34 946 555 111",
    email: "admin@gasobusturia.example",
    address: "BI-2235, Busturia",
    category: "vehiculo",
    paymentTerms: "Tarjeta",
    notes: "Combustible furgoneta técnica.",
  },
];

const purchases: PurchaseDocument[] = [
  {
    id: "po-1",
    supplierId: "sp-1",
    type: "pedido_proveedor",
    reference: "PED-PRO-2026-014",
    status: "pendiente",
    date: new Date().toISOString().slice(0, 10),
    dueDate: new Date().toISOString().slice(0, 10),
    subtotal: 132,
    vat: 27.72,
    total: 159.72,
    linkedJobId: "jb-2",
    receiptAttached: false,
    notes: "Bomba desagüe y consumibles para reparación pendiente.",
  },
  {
    id: "po-2",
    supplierId: "sp-2",
    type: "factura_proveedor",
    reference: "FP-2026-088",
    status: "pagado",
    date: new Date().toISOString().slice(0, 10),
    dueDate: new Date().toISOString().slice(0, 10),
    subtotal: 96,
    vat: 20.16,
    total: 116.16,
    linkedJobId: "jb-5",
    receiptAttached: true,
    notes: "Factura recibida y lista para libro de facturas recibidas.",
  },
  {
    id: "po-3",
    supplierId: "sp-3",
    type: "ticket",
    reference: "TK-2026-441",
    status: "pagado",
    date: new Date().toISOString().slice(0, 10),
    dueDate: new Date().toISOString().slice(0, 10),
    subtotal: 58.2,
    vat: 12.22,
    total: 70.42,
    receiptAttached: false,
    notes: "Ticket pendiente de adjuntar foto.",
  },
];

const creditNotes: CreditNote[] = [
  {
    id: "cn-1",
    invoiceId: "inv-1",
    reference: "ABO-2026-004",
    status: "borrador",
    date: new Date().toISOString().slice(0, 10),
    reason: "Ajuste pendiente si el cliente devuelve una pieza no instalada.",
    subtotal: 12,
    vat: 2.52,
    total: 14.52,
  },
];

const events: JobEvent[] = jobs.flatMap((job) => [
  {
    id: `ev-${job.id}-1`,
    jobId: job.id,
    eventType: "trabajo_creado",
    fromStatus: "",
    toStatus: "nuevo",
    note: `Creado desde ${job.origin}`,
    createdAt: nowIso(),
  },
  {
    id: `ev-${job.id}-2`,
    jobId: job.id,
    eventType: "estado_actualizado",
    fromStatus: "nuevo",
    toStatus: job.status,
    note: "Actualización inicial",
    createdAt: nowIso(),
  },
]);

const knowledge: KnowledgeEntry[] = [
  {
    id: "kb-1",
    category: "lavadora",
    brand: "Balay",
    model: "3TS986X",
    symptom: "No desagua",
    probableCause: "Bomba bloqueada",
    solution: "Sustitución de bomba y limpieza de filtro",
    partsUsed: "Bomba desagüe lavadora",
    confidence: "alta",
    sourceJobId: "jb-2",
    notes: "Comprobar también manguera de salida",
  },
];

export const demoAppData: AppData = {
  clients,
  assets,
  materials,
  jobs,
  invoices,
  estimates,
  expenses,
  suppliers,
  purchases,
  creditNotes,
  events,
  knowledge,
  sequence: 6,
};
